### ISSUE TITLE
Flash with MasterDetailPage navigation

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [Binwell/Order-King-Mobile-Core#1]
Hello.

When calling the SetMainMasterDetailPage method, you may notice flashes when navigating to other pages using the hamburger menu.

Steps to reproduce:
You can clone the latest version of OrderKingDemo project and also notice the flashes, but flashes are not as big as in our project.

Description: 
For a while the screen becomes completely white when you navigate

Th, best regards.
Nikita

**Comment by SlavaChernikoff** [comment]
Yep, there is an issue with flashing appeared in Xamarin.Forms 2.5 with current NavigationService. We'll check how to fix it later.

**Comment by SlavaChernikoff** [comment]
@Goncharuk-Nikita could you please re-check the latest version with fixes from @maukur . Issue should be fixed
